[pyprland]

plugins = [
  "scratchpads",
  "magnify",
]

#[scratchpads.term]
#animation = "fromTop"
#command = "xfce4-terminal --class xfce4-terminal-dropterm"
#class = "xfce4-terminal-dropterm"
#size = "75% 60%"

[scratchpads.term]
animation = "fromTop"
command = "xfce4-terminal --class xfce4-terminal-dropterm"
class = "xfce4-terminal-dropterm"
size = "75% 60%"

